# Generated by Django 3.2.6 on 2021-08-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='Alerts',
        ),
    ]
