# Generated by Django 3.2.6 on 2021-08-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alert_alerts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
