# Generated by Django 3.2.6 on 2021-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_rename_alerts_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('snapshot', models.BinaryField()),
            ],
        ),
    ]
